version: '3'

networks:
  mynetwork:  # Define your custom network

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mynetwork  # Use the same custom network

  nodejs-app:
    build:
      context: /mnt/c/Users/aishv/OneDrive/Desktop/d3.js_mongodb
      dockerfile: /mnt/c/Users/aishv/OneDrive/Desktop/d3.js_mongodb/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - mynetwork  # Define a custom network


